// <auto-generated />
using System;
using CanadaDeals.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace CanadaDeals.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DealsDbContext))]
    [Migration("20260824162651_AddProductImagePublishing")]
    partial class AddProductImagePublishing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CanadaDeals.Domain.Accounts.SavedProduct", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("SavedProducts");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Administration.AdminAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityType", "EntityId", "CreatedAt");

                    b.ToTable("AdminAuditEvents");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Affiliates.AffiliateLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AffiliateProgramId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("LastValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<Guid>("RetailerListingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RevalidateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TrackingUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("AffiliateProgramId", "Status");

                    b.HasIndex("RetailerListingId", "Status", "RevalidateAt");

                    b.ToTable("AffiliateLinks");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Affiliates.AffiliateProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("AllowsDeepLinking")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationDomainsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("MediaPropertyId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderLinkReference")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("ProviderProgramId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("RelationshipEvidenceReference")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("RelationshipValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RetailerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TrackingDomainsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RetailerId", "Provider")
                        .IsUnique();

                    b.HasIndex("Status", "UpdatedAt");

                    b.ToTable("AffiliatePrograms");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Affiliates.ClickEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AffiliateLinkId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AffiliateProgramId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Placement")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("RetailerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RetailerListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StoreAffiliateDestinationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AffiliateProgramId");

                    b.HasIndex("AffiliateLinkId", "CreatedAt");

                    b.HasIndex("RetailerId", "CreatedAt");

                    b.HasIndex("RetailerListingId", "CreatedAt");

                    b.HasIndex("StoreAffiliateDestinationId", "CreatedAt");

                    b.ToTable("ClickEvents", t =>
                        {
                            t.HasCheckConstraint("CK_ClickEvents_Source", "(\"AffiliateLinkId\" IS NOT NULL AND \"RetailerListingId\" IS NOT NULL AND \"StoreAffiliateDestinationId\" IS NULL) OR (\"AffiliateLinkId\" IS NULL AND \"RetailerListingId\" IS NULL AND \"StoreAffiliateDestinationId\" IS NOT NULL AND \"RetailerId\" IS NOT NULL AND \"AffiliateProgramId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("CanadaDeals.Domain.Affiliates.StoreAffiliateDestination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AffiliateProgramId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("LastValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<Guid>("RetailerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RevalidateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TrackingUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("AffiliateProgramId")
                        .IsUnique();

                    b.HasIndex("RetailerId", "Status", "RevalidateAt");

                    b.ToTable("StoreAffiliateDestinations");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Alerts.NotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTimeOffset?>("LastAttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastProviderEventAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PriceAlertId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PriceObservationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProviderAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<decimal>("QualifyingPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("TargetPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("TargetVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PriceObservationId");

                    b.HasIndex("ProviderMessageId")
                        .IsUnique()
                        .HasFilter("\"ProviderMessageId\" IS NOT NULL");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("PriceAlertId", "TargetVersion", "PriceObservationId")
                        .IsUnique();

                    b.ToTable("NotificationDeliveries");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Alerts.PriceAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ConsentGrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConsentVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("IsBelowTargetCycle")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastEvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastTriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TargetPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("TargetVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("Status", "LastEvaluatedAt");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("PriceAlerts", t =>
                        {
                            t.HasCheckConstraint("CK_PriceAlerts_TargetPrice", "\"TargetPrice\" > 0 AND \"TargetPrice\" <= 1000000");

                            t.HasCheckConstraint("CK_PriceAlerts_TargetVersion", "\"TargetVersion\" > 0");
                        });
                });

            modelBuilder.Entity("CanadaDeals.Domain.Catalog.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Catalog.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("IsEnabled", "Name");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Gtin")
                        .HasColumnType("text");

                    b.Property<string>("ManufacturerPartNumber")
                        .HasColumnType("text");

                    b.Property<string>("ModelNumber")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedManufacturerPartNumber")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedModelNumber")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("SearchDocument")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "SearchDocument" });

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("VariantAttributesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Gtin");

                    b.HasIndex("NormalizedManufacturerPartNumber");

                    b.HasIndex("NormalizedModelNumber");

                    b.HasIndex("SearchDocument");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchDocument"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchDocument"), new[] { "gin_trgm_ops" });

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("BrandId", "ModelNumber");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Catalog.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedPlacements")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MerchantPolicyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Origin")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("RightsEvidenceReference")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("SourceListingId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("MerchantPolicyId");

                    b.HasIndex("SourceListingId");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("ProductId", "State", "CreatedAt");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Integrations.RakutenAdvertiserCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdvertiserMid")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("AdvertiserName")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<int>("AdvertiserStatus")
                        .HasColumnType("integer");

                    b.Property<string>("AdvertiserUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("AffiliateEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool?>("CanadaRelevant")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CapabilityCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CatalogEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("DeepLinksAvailable")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MerchantPolicyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PartnershipApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PartnershipStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PartnershipStatusUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ProductFeedAvailable")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RetailerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShipsToJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserMid")
                        .IsUnique();

                    b.HasIndex("MerchantPolicyId");

                    b.HasIndex("RetailerId");

                    b.HasIndex("PartnershipStatus", "AdvertiserStatus", "CapabilityCheckedAt");

                    b.ToTable("RakutenAdvertiserCapabilities");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Integrations.RakutenImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdvertiserMid")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("DryRun")
                        .HasColumnType("boolean");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ListingsCreated")
                        .HasColumnType("integer");

                    b.Property<int>("ListingsUpdated")
                        .HasColumnType("integer");

                    b.Property<int>("ObservationsCreated")
                        .HasColumnType("integer");

                    b.Property<int>("PagesFetched")
                        .HasColumnType("integer");

                    b.Property<int>("PolicyBlocked")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsReceived")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewCandidates")
                        .HasColumnType("integer");

                    b.Property<int>("Skipped")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserMid", "StartedAt");

                    b.HasIndex("Status", "StartedAt");

                    b.ToTable("RakutenImportRuns");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Integrations.RakutenSourceMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdvertiserMid")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RetailerListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceListingKey")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.HasKey("Id");

                    b.HasIndex("RetailerListingId")
                        .IsUnique();

                    b.HasIndex("AdvertiserMid", "SourceListingKey")
                        .IsUnique();

                    b.ToTable("RakutenSourceMappings");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Notifications.AccountConfirmationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTimeOffset?>("LastAttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastProviderEventAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProviderAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProviderMessageId")
                        .IsUnique()
                        .HasFilter("\"ProviderMessageId\" IS NOT NULL");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("AccountConfirmationDeliveries");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Notifications.ControlledEmailCapture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("TextBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("DestinationAddress", "CapturedAt");

                    b.ToTable("ControlledEmailCaptures");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Notifications.EmailSuppression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedAddress")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedAddress")
                        .IsUnique();

                    b.ToTable("EmailSuppressions");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Notifications.ProcessedEmailWebhook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("ProviderCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "EventId")
                        .IsUnique();

                    b.ToTable("ProcessedEmailWebhooks");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Policies.MerchantPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AllowAffiliateLinks")
                        .HasColumnType("integer");

                    b.Property<int>("AllowImageCaching")
                        .HasColumnType("integer");

                    b.Property<int>("AllowMetadataCaching")
                        .HasColumnType("integer");

                    b.Property<int>("AllowPriceHistory")
                        .HasColumnType("integer");

                    b.Property<int>("AllowPriceStorage")
                        .HasColumnType("integer");

                    b.Property<string>("AllowedComparison")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("DataResidencyNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisclosureText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("LinkExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PriceMaxAgeHours")
                        .HasColumnType("integer");

                    b.Property<int?>("RawRetentionDays")
                        .HasColumnType("integer");

                    b.Property<string>("RequiredAttribution")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SourceKey")
                        .IsUnique();

                    b.ToTable("MerchantPolicies");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Reporting.ListingIssueReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<Guid>("RetailerListingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RetailerListingId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("ListingIssueReports");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Retailers.PriceObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPermitted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RetailerListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("RetailerListingId", "ObservedAt", "SourceHash")
                        .IsUnique();

                    b.ToTable("PriceObservations");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Retailers.Retailer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Retailers");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Retailers.RetailerListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovedAffiliateDestinationReference")
                        .HasColumnType("text");

                    b.Property<string>("BundleContents")
                        .HasColumnType("text");

                    b.Property<int>("Condition")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CurrentPriceAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("CurrentPriceCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("Evidence")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalIdentifiersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ExternalListingId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Freshness")
                        .HasColumnType("integer");

                    b.Property<int>("History")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsMarketplaceSeller")
                        .HasColumnType("boolean");

                    b.Property<int>("MatchState")
                        .HasColumnType("integer");

                    b.Property<Guid>("MerchantPolicyId")
                        .HasColumnType("uuid");

                    b.Property<int>("OnlineAvailability")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("PackQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RegionAvailabilityContext")
                        .HasColumnType("text");

                    b.Property<Guid>("RetailerId")
                        .HasColumnType("uuid");

                    b.Property<string>("RetailerSku")
                        .HasColumnType("text");

                    b.Property<string>("Seller")
                        .HasColumnType("text");

                    b.Property<string>("ShippingContext")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SourceObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VariantAttributesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPriceAmount");

                    b.HasIndex("MerchantPolicyId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SourceObservedAt");

                    b.HasIndex("OnlineAvailability", "MatchState");

                    b.HasIndex("RetailerId", "ExternalListingId")
                        .IsUnique();

                    b.ToTable("RetailerListings");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Retailers.StoreBannerAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("StoreBannerAssets");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Retailers.StoreBannerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedPlacement")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("AssetEvidenceReference")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("AssetPath")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("AssetProvider")
                        .HasColumnType("integer");

                    b.Property<int>("AssetSource")
                        .HasColumnType("integer");

                    b.Property<int>("BannerOrder")
                        .HasColumnType("integer");

                    b.Property<int>("BrandAssetPolicy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EffectiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RetailerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("RetailerId")
                        .IsUnique();

                    b.HasIndex("IsEnabled", "BannerOrder");

                    b.ToTable("StoreBannerProfiles");
                });

            modelBuilder.Entity("CanadaDeals.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CanadaDeals.Domain.Accounts.SavedProduct", b =>
                {
                    b.HasOne("CanadaDeals.Domain.Catalog.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CanadaDeals.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Administration.AdminAuditEvent", b =>
                {
                    b.HasOne("CanadaDeals.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CanadaDeals.Domain.Affiliates.AffiliateLink", b =>
                {
                    b.HasOne("CanadaDeals.Domain.Affiliates.AffiliateProgram", "AffiliateProgram")
                        .WithMany()
                        .HasForeignKey("AffiliateProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CanadaDeals.Domain.Retailers.RetailerListing", "RetailerListing")
                        .WithMany("AffiliateLinks")
                        .HasForeignKey("RetailerListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AffiliateProgram");

                    b.Navigation("RetailerListing");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Affiliates.AffiliateProgram", b =>
                {
                    b.HasOne("CanadaDeals.Domain.Retailers.Retailer", "Retailer")
                        .WithMany()
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Retailer");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Affiliates.ClickEvent", b =>
                {
                    b.HasOne("CanadaDeals.Domain.Affiliates.AffiliateLink", "AffiliateLink")
                        .WithMany()
                        .HasForeignKey("AffiliateLinkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CanadaDeals.Domain.Affiliates.AffiliateProgram", null)
                        .WithMany()
                        .HasForeignKey("AffiliateProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CanadaDeals.Domain.Retailers.Retailer", null)
                        .WithMany()
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CanadaDeals.Domain.Retailers.RetailerListing", null)
                        .WithMany()
                        .HasForeignKey("RetailerListingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CanadaDeals.Domain.Affiliates.StoreAffiliateDestination", "StoreAffiliateDestination")
                        .WithMany()
                        .HasForeignKey("StoreAffiliateDestinationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AffiliateLink");

                    b.Navigation("StoreAffiliateDestination");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Affiliates.StoreAffiliateDestination", b =>
                {
                    b.HasOne("CanadaDeals.Domain.Affiliates.AffiliateProgram", "AffiliateProgram")
                        .WithMany()
                        .HasForeignKey("AffiliateProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CanadaDeals.Domain.Retailers.Retailer", null)
                        .WithMany()
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AffiliateProgram");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Alerts.NotificationDelivery", b =>
                {
                    b.HasOne("CanadaDeals.Domain.Alerts.PriceAlert", "PriceAlert")
                        .WithMany()
                        .HasForeignKey("PriceAlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CanadaDeals.Domain.Retailers.PriceObservation", null)
                        .WithMany()
                        .HasForeignKey("PriceObservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PriceAlert");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Alerts.PriceAlert", b =>
                {
                    b.HasOne("CanadaDeals.Domain.Catalog.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CanadaDeals.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Catalog.Product", b =>
                {
                    b.HasOne("CanadaDeals.Domain.Catalog.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CanadaDeals.Domain.Catalog.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Catalog.ProductImage", b =>
                {
                    b.HasOne("CanadaDeals.Domain.Policies.MerchantPolicy", null)
                        .WithMany()
                        .HasForeignKey("MerchantPolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CanadaDeals.Domain.Catalog.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CanadaDeals.Domain.Retailers.RetailerListing", null)
                        .WithMany()
                        .HasForeignKey("SourceListingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CanadaDeals.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Integrations.RakutenAdvertiserCapability", b =>
                {
                    b.HasOne("CanadaDeals.Domain.Policies.MerchantPolicy", "MerchantPolicy")
                        .WithMany()
                        .HasForeignKey("MerchantPolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CanadaDeals.Domain.Retailers.Retailer", "Retailer")
                        .WithMany()
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MerchantPolicy");

                    b.Navigation("Retailer");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Integrations.RakutenSourceMapping", b =>
                {
                    b.HasOne("CanadaDeals.Domain.Retailers.RetailerListing", "RetailerListing")
                        .WithMany()
                        .HasForeignKey("RetailerListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RetailerListing");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Notifications.AccountConfirmationDelivery", b =>
                {
                    b.HasOne("CanadaDeals.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CanadaDeals.Domain.Reporting.ListingIssueReport", b =>
                {
                    b.HasOne("CanadaDeals.Domain.Retailers.RetailerListing", "RetailerListing")
                        .WithMany()
                        .HasForeignKey("RetailerListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RetailerListing");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Retailers.PriceObservation", b =>
                {
                    b.HasOne("CanadaDeals.Domain.Retailers.RetailerListing", null)
                        .WithMany()
                        .HasForeignKey("RetailerListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CanadaDeals.Domain.Retailers.RetailerListing", b =>
                {
                    b.HasOne("CanadaDeals.Domain.Policies.MerchantPolicy", "MerchantPolicy")
                        .WithMany()
                        .HasForeignKey("MerchantPolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CanadaDeals.Domain.Catalog.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CanadaDeals.Domain.Retailers.Retailer", "Retailer")
                        .WithMany()
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MerchantPolicy");

                    b.Navigation("Product");

                    b.Navigation("Retailer");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Retailers.StoreBannerAsset", b =>
                {
                    b.HasOne("CanadaDeals.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CanadaDeals.Domain.Retailers.StoreBannerProfile", b =>
                {
                    b.HasOne("CanadaDeals.Domain.Retailers.Retailer", "Retailer")
                        .WithMany()
                        .HasForeignKey("RetailerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Retailer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CanadaDeals.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CanadaDeals.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CanadaDeals.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CanadaDeals.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CanadaDeals.Domain.Catalog.Product", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("CanadaDeals.Domain.Retailers.RetailerListing", b =>
                {
                    b.Navigation("AffiliateLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
